// <auto-generated />
namespace Fil_rouge_evente.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class chgt_nom_numeroCompte_numeroCarte : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chgt_nom_numeroCompte_numeroCarte));
        
        string IMigrationMetadata.Id
        {
            get { return "201610121259031_chgt_nom_numeroCompte_numeroCarte"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
