// <auto-generated />
namespace Fil_rouge_evente.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CreationBDD : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreationBDD));
        
        string IMigrationMetadata.Id
        {
            get { return "201610141032343_CreationBDD"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
